#!/usr/bin/env python3
"""Generate synthetic fixtures so replay mode works before a real draft exists.

Real fixtures from `probe_draft.py --record` are always better — these exist so
the UI, the recommender and the team report can be exercised end to end with no
credentials at all.

    python scripts/make_fixtures.py                    # a whole 12-team draft into samples/
    python scripts/make_fixtures.py --frames 40        # just the first 40 picks
    python scripts/make_fixtures.py --out /tmp/replay  # somewhere else entirely

The script refuses to write into a directory holding JSON it did not generate.
A real dump from `dump_samples.py` is unrecoverable — `samples/**` is gitignored
because it carries live league and member data — and an earlier version of this
script deleted `draft_detail_*.json` on sight. Hence the marker file and the
guard; `--force` is the deliberate override.
"""
from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

DEFAULT_OUT = Path(__file__).resolve().parent.parent / "samples"
MARKER = ".synthetic"          # "this directory is disposable"

TEAM_COUNT = 12
ROUNDS = 16
POSITIONS = [(2, "RB", 90), (3, "WR", 130), (1, "QB", 32), (4, "TE", 30), (16, "DST", 20), (5, "K", 20)]
# What a position is worth on draft day beyond its raw projection. ESPN's ranks are
# ADP-like, not projection order — a QB outscores every RB and still goes rounds
# later, and kickers rank near the bottom of the board however many points they
# score. Without this the fixtures rank QB1 first, and every sane pick after it
# scores as a reach against its rank.
DRAFT_PREMIUM = {"RB": 60.0, "WR": 50.0, "QB": 0.0, "TE": 25.0, "DST": -60.0, "K": -80.0}
# How many of a position a roster will carry — starters, flex, and sane bench depth.
LIMITS = {"QB": 2, "RB": 6, "WR": 6, "TE": 2, "DST": 1, "K": 1}


def guard(out: Path, force: bool) -> None:
    """Never clobber a directory that holds someone's real dump."""
    if force or not out.exists():
        return
    existing = sorted(p.name for p in out.glob("*.json"))
    if existing and not (out / MARKER).exists():
        print(f"refusing to write into {out}: it holds JSON this script did not generate\n"
              f"  found: {', '.join(existing[:4])}{' …' if len(existing) > 4 else ''}\n"
              f"  those files are gitignored and may be the only copy — move them aside,\n"
              f"  pass --out DIR to write elsewhere, or --force if you are certain.",
              file=sys.stderr)
        raise SystemExit(2)


def wants(position: str, filled: dict[str, int], rnd: int, rounds: int) -> bool:
    """Roughly how a human drafts: starters first, one QB and one TE before the
    depth pieces, and the kicker and defense in the last rounds where they belong.

    Without this the fixtures are pure best-available, which makes every generated
    roster shapeless — and roster shape is exactly what the recommender's roster
    need term (§7) and the team report are supposed to react to.
    """
    unfilled_specialists = [p for p in ("DST", "K") if filled.get(p, 0) == 0]
    if rnd > rounds - len(unfilled_specialists):
        return position in unfilled_specialists
    if position in ("K", "DST"):
        return False
    if position == "QB" and filled.get("QB", 0) >= 1 and rnd < 12:
        return False
    if position == "TE" and filled.get("TE", 0) >= 1 and rnd < 11:
        return False
    return filled.get(position, 0) < LIMITS[position]


def build(out: Path, frames: int, seed: int) -> None:
    rng = random.Random(seed)
    out.mkdir(parents=True, exist_ok=True)
    (out / MARKER).write_text("Generated by scripts/make_fixtures.py — safe to delete.\n")

    teams = [
        {"id": i, "location": "Team", "nickname": f"{i:02d}",
         "name": name, "owners": [f"{{OWNER-{i}}}"]}
        for i, name in enumerate([
            "Gridiron Gang", "Purple Reign", "Cleats & Cleavage", "Sunday Scaries",
            "The Waiver Wire", "End Zone Militia", "Blitz Brigade", "Hail Mary Inc",
            "Fourth & Long", "Play Action Heroes", "Red Zone Rats", "Pylon Patrol",
        ], start=1)
    ]
    members = [{"id": f"{{OWNER-{i}}}", "firstName": "Owner", "lastName": str(i),
                "displayName": f"owner{i}"} for i in range(1, TEAM_COUNT + 1)]

    pick_order = list(range(1, TEAM_COUNT + 1))
    rng.shuffle(pick_order)

    name_by_id = {1: "QB", 2: "RB", 3: "WR", 4: "TE", 5: "K", 16: "DST"}
    players, pid = [], 100000
    for position_id, position, count in POSITIONS:
        for n in range(count):
            pid += 1
            base = {1: 300, 2: 260, 3: 250, 4: 180, 5: 130, 16: 130}[position_id]
            proj = max(20.0, base - n * rng.uniform(2.5, 6.0))
            players.append({
                "id": pid,
                "player": {
                    "id": pid,
                    "fullName": f"{position} Player {n + 1}",
                    "defaultPositionId": position_id,
                    "proTeamId": rng.choice([1, 2, 6, 12, 21, 25, 33, 34]),
                    "draftRanksByRankType": {
                        "PPR": {"rank": 0, "auctionValue": max(1, int(proj / 6))},
                        "STANDARD": {"rank": 0, "auctionValue": max(1, int(proj / 6))},
                    },
                    "stats": [{"statSourceId": 1, "statSplitTypeId": 0,
                               "seasonId": 2026, "appliedTotal": round(proj, 1)}],
                },
            })

    def draft_value(entry: dict) -> float:
        position = name_by_id[entry["player"]["defaultPositionId"]]
        return entry["player"]["stats"][0]["appliedTotal"] + DRAFT_PREMIUM[position]

    players.sort(key=lambda e: -draft_value(e))
    for i, entry in enumerate(players, start=1):
        for rank_type in entry["player"]["draftRanksByRankType"].values():
            rank_type["rank"] = i
    # The pool is still emitted in rank order, so rank 1 is the first entry.
    players.sort(key=lambda e: e["player"]["draftRanksByRankType"]["PPR"]["rank"])

    setup = {
        "teams": teams,
        "members": members,
        "settings": {
            "draftSettings": {"type": "SNAKE", "pickOrder": pick_order},
            "rosterSettings": {"lineupSlotCounts": {
                "0": 1, "2": 2, "4": 2, "6": 1, "23": 1, "16": 1, "17": 1, "20": 7}},
        },
        "draftDetail": {"drafted": False, "inProgress": True, "picks": []},
    }
    (out / "league_setup.json").write_text(json.dumps(setup, indent=2))
    (out / "player_pool.json").write_text(json.dumps({"players": players}, indent=2))

    snake = []
    for rnd in range(ROUNDS):
        snake.extend(pick_order if rnd % 2 == 0 else list(reversed(pick_order)))

    total = len(snake) if frames <= 0 else min(frames, len(snake))
    position_of = {e["id"]: e["player"]["defaultPositionId"] for e in players}

    for old in out.glob("draft_detail_*.json"):
        old.unlink()

    filled: dict[int, dict[str, int]] = {t["id"]: {} for t in teams}
    taken: set[int] = set()
    picks: list[dict] = []

    for overall, team_id in enumerate(snake[:total], start=1):
        rnd = (overall - 1) // TEAM_COUNT + 1
        board = [e for e in players if e["id"] not in taken]
        window = board[:8] if rng.random() < 0.25 else board[:3]   # occasional reach
        chosen = next(
            (e for e in window
             if wants(name_by_id[position_of[e["id"]]], filled[team_id], rnd, ROUNDS)),
            next((e for e in board
                  if wants(name_by_id[position_of[e["id"]]], filled[team_id], rnd, ROUNDS)),
                 board[0]))

        taken.add(chosen["id"])
        position = name_by_id[position_of[chosen["id"]]]
        filled[team_id][position] = filled[team_id].get(position, 0) + 1
        picks.append({
            "id": overall, "overallPickNumber": overall,
            "roundId": rnd, "roundPickNumber": (overall - 1) % TEAM_COUNT + 1,
            "teamId": team_id, "playerId": chosen["id"],
            "keeper": False, "autoDraftTypeId": 0,
        })
        # One frame per pick, so replay advances the draft one pick per poll. The
        # last frame of a full draft flips to drafted/COMPLETE, which is the only
        # way the replay path ever exercises the end-of-draft state.
        done = overall == len(snake)
        frame = {"draftDetail": {"drafted": done, "inProgress": not done,
                                 "picks": [dict(p) for p in picks]}}
        (out / f"draft_detail_{overall:04d}.json").write_text(json.dumps(frame))

    my_team = snake[3]
    print(f"wrote fixtures to {out}")
    print(f"  {len(players)} players, {len(picks)} pick frames, "
          f"{'complete draft' if total == len(snake) else f'{total} of {len(snake)} picks'}")
    print(f"  set MY_TEAM_ID={my_team} (picks 4th in round 1) to watch your own turns")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT,
                        help=f"directory to write into (default: {DEFAULT_OUT})")
    parser.add_argument("--frames", type=int, default=0,
                        help="how many picks to generate; 0 (default) drafts every round")
    parser.add_argument("--seed", type=int, default=7, help="rng seed (default: 7)")
    parser.add_argument("--force", action="store_true",
                        help="write even if the directory holds JSON this script did not generate")
    args = parser.parse_args()

    guard(args.out, args.force)
    build(args.out, args.frames, args.seed)


if __name__ == "__main__":
    main()
